---
kind: pipeline
type: docker
name: default-build

workspace:
  path: /stargaze

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
  - name: restore-cache
    image: meltwater/drone-cache:dev
    volumes:
      - name: cache
        path: /go
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: minio_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: minio_secret_key
    pull: true
    settings:
      restore: true
      bucket:
        from_secret: minio_bucket
      region: us-east-1
      mount:
        - '/go/pkg/mod'

  - name: test
    image: publicawesome/golang:1.17.0-devtooling
    volumes:
      - name: cache
        path: /go
    commands:
      - ./scripts/go-test.sh
    environment:
      GOPROXY: http://goproxy
  - name: build
    image: golang:1.17-alpine3.14
    volumes:
      - name: cache
        path: /go
    commands:
      - apk add --no-cache ca-certificates build-base git
      - wget https://github.com/CosmWasm/wasmvm/releases/download/v0.14.0/libwasmvm_muslc.a -O /lib/libwasmvm_muslc.a
      - sha256sum /lib/libwasmvm_muslc.a | grep 220b85158d1ae72008f099a7ddafe27f6374518816dd5873fd8be272c5418026
      - FAUCET_ENABLED=true LEDGER_ENABLED=false BUILD_TAGS=muslc make build
    environment:
      GOPROXY: http://goproxy
  - name: coverage
    image: plugins/codecov
    volumes:
      - name: cache
        path: /go
    settings:
      required: true
      token:
        from_secret: codecov-token
    when:
      event:
        - push
        - pull_request
  - name: publish-test
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile.test
      repo: rocketprotocol/rocketzone-relayer-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
    when:
      event:
        - push
      branch: ibc
  - name: publish-docker
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile
      repo: publicawesome/stargaze
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - develop
    when:
      event:
        - push
      branch:
        - develop
  - name: trigger
    image: plugins/downstream
    settings:
      server:
        from_secret: ci_server
      token:
        from_secret: ci_token
      deploy: deploy-devnet
      last_successful: true
      fork: true
      repositories:
        from_secret: downstream_repositories
    when:
      branch: 
        - develop
      event:
        - push
  - name: docker_release
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile
      repo: publicawesome/stargaze
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
    when:
      event:
        - tag

  - name: release
    image: golang:1.17.0
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - curl -sL https://git.io/goreleaser | bash
    environment:
      GOPROXY: http://goproxy
    when:
      event:
        - tag
  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    volumes:
      - name: cache
        path: /go
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: minio_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: minio_secret_key
    pull: true
    settings:
      rebuild: true
      bucket:
        from_secret: minio_bucket
      region: us-east-1
      mount:
        - '/go/pkg/mod'
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id: 
        from_secret: discord_webhook_id
      webhook_token: 
        from_secret: discord_webhook_token
    when:
      status: [success, failure]

volumes:
- name: cache
  temp: {}
---
kind: pipeline
type: docker
name: ibc-integration-test

steps:
  - name: gaia
    image: publicawesome/gaia:5.0.5
    detach: true
    commands:
      - ./scripts/ci/setup-gaia.sh
    environment:
      GOPROXY: http://goproxy
  - name: stargaze
    image: publicawesome/golang:1.17.0-devtooling
    commands:
      - ./scripts/ci/setup-stargaze.sh
    environment:
      GOPROXY: http://goproxy
    detach: true
  - name: relayer
    image: publicawesome/hermes:latest
    commands:
      - /bin/bash ./scripts/ci/setup-relayer.sh

  - name: relayer-start
    image: publicawesome/hermes:latest
    commands:
      - /bin/bash ./scripts/ci/start-relayer.sh
    detach: true
  - name: relayer-sender
    image: publicawesome/hermes:latest
    commands:
      - /bin/bash ./scripts/ci/transfer-relayer.sh
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id: 
        from_secret: discord_webhook_id
      webhook_token: 
        from_secret: discord_webhook_token
    when:
      status: [success, failure]

trigger:
  branch:
    - main
  event:
    - pull_request
    - push
depends_on:
  - default-build
---
kind: signature
hmac: f7cbdb2322ad2a5e8a9872926b42fcede56efaa0cbedb8285037a00c848f3930

...
