accounts:
  - name: alice
    coins: ["20000token", "200000000uacarb"]
  - name: bob
    coins: ["10000token", "100000000uacarb"]
build:
  binary: "acarbd"
  main: "cmd/acarbd"
validator:
  name: alice
  staked: "100000000uacarb"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5token", "100000uacarb"]
genesis:
  chain_id: "alteredcarbon-localnet-1"
  app_state:
    staking:
      params:
        bond_denom: "uacarb"
init:
  home: "$HOME/.acarbd"
